# Generated by Django 4.2.2 on 2023-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Администратор организации', 'Администратор организации'), ('Главный администратор', 'Главный администратор')], default='Пользователь', max_length=255),
        ),
    ]
