# Generated by Django 4.2.2 on 2023-07-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0003_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
