# Generated by Django 4.2.2 on 2023-07-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_app', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
